---
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'demo-express-api-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['demo-express-api:6500']
